class GetTokenError(Exception): ...


class ServerResponseFail(Exception): ...


class ParseResponseError(Exception): ...


class ResolveCaptchaFail(Exception): ...


class ServerLimitError(Exception): ...
